"""
Catalogue des applications supportées sur Windows et Linux.
Chaque application contient ses identifiants respectifs pour :
- Windows (Winget ID officiel)
- Linux (Flatpak App ID ou nom de paquet APT)
"""

CATEGORIES = [
    "Toutes",
    "Navigateurs",
    "Communication",
    "Gaming",
    "Musique & Médias",
    "Développement",
    "Utilitaires & Sécurité",
    "Graphisme & Création",
    "Bureautique",
]

DEFAULT_CATALOG = [
    # --- NAVIGATEURS ---
    {
        "id": "brave",
        "name": "Brave Browser",
        "category": "Navigateurs",
        "desc": "Navigateur rapide axé sur la vie privée et le blocage de pubs",
        "icon": "🦁",
        "windows_id": "Brave.Brave",
        "linux_id": "com.brave.Browser",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "chrome",
        "name": "Google Chrome",
        "category": "Navigateurs",
        "desc": "Navigateur web officiel de Google, rapide et synchronisé",
        "icon": "🌐",
        "windows_id": "Google.Chrome",
        "linux_id": "com.google.Chrome",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "firefox",
        "name": "Mozilla Firefox",
        "category": "Navigateurs",
        "desc": "Navigateur web libre, respectueux de la vie privée et personnalisable",
        "icon": "🦊",
        "windows_id": "Mozilla.Firefox",
        "linux_id": "org.mozilla.firefox",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "edge",
        "name": "Microsoft Edge",
        "category": "Navigateurs",
        "desc": "Navigateur optimisé de Microsoft avec outils Copilot intégrés",
        "icon": "🌊",
        "windows_id": "Microsoft.Edge",
        "linux_id": "com.microsoft.Edge",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "opera",
        "name": "Opera One",
        "category": "Navigateurs",
        "desc": "Navigateur innovant avec VPN et messageries intégrées",
        "icon": "⭕",
        "windows_id": "Opera.Opera",
        "linux_id": "com.opera.Opera",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "tor",
        "name": "Tor Browser",
        "category": "Navigateurs",
        "desc": "Navigation anonyme et sécurisée via le réseau décentralisé Tor",
        "icon": "🧅",
        "windows_id": "TorProject.TorBrowser",
        "linux_id": "com.github.micahflee.torbrowser-launcher",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- COMMUNICATION ---
    {
        "id": "discord",
        "name": "Discord",
        "category": "Communication",
        "desc": "Chat vocal, vidéo et texte pour communautés et amis",
        "icon": "💬",
        "windows_id": "Discord.Discord",
        "linux_id": "com.discordapp.Discord",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "telegram",
        "name": "Telegram Desktop",
        "category": "Communication",
        "desc": "Messagerie instantanée ultra-rapide, chiffrée et synchronisée",
        "icon": "✈️",
        "windows_id": "Telegram.TelegramDesktop",
        "linux_id": "org.telegram.desktop",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "signal",
        "name": "Signal Desktop",
        "category": "Communication",
        "desc": "Messagerie sécurisée avec chiffrement de bout en bout strict",
        "icon": "🔒",
        "windows_id": "OpenWhisperSystems.Signal",
        "linux_id": "org.signal.Signal",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "whatsapp",
        "name": "WhatsApp",
        "category": "Communication",
        "desc": "Application officielle de messagerie et appels WhatsApp",
        "icon": "🟢",
        "windows_id": "WhatsApp.WhatsApp",
        "linux_id": "com.rtosta.zapzap",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "slack",
        "name": "Slack",
        "category": "Communication",
        "desc": "Plateforme de collaboration et communication pour équipes",
        "icon": "💼",
        "windows_id": "SlackTechnologies.Slack",
        "linux_id": "com.slack.Slack",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "zoom",
        "name": "Zoom Workplace",
        "category": "Communication",
        "desc": "Visioconférences et réunions virtuelles haute définition",
        "icon": "📹",
        "windows_id": "Zoom.Zoom",
        "linux_id": "us.zoom.Zoom",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- GAMING ---
    {
        "id": "steam",
        "name": "Steam",
        "category": "Gaming",
        "desc": "La plus grande plateforme de distribution de jeux vidéo sur PC",
        "icon": "🎮",
        "windows_id": "Valve.Steam",
        "linux_id": "com.valvesoftware.Steam",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "epicgames",
        "name": "Epic Games Launcher",
        "category": "Gaming",
        "desc": "Boutique Epic Games (Fortnite, Unreal Engine, jeux gratuits)",
        "icon": "⚡",
        "windows_id": "EpicGames.EpicGamesLauncher",
        "linux_id": "com.heroicgameslauncher.hgl",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "heroic",
        "name": "Heroic Games Launcher",
        "category": "Gaming",
        "desc": "Lanceur open-source pour jeux Epic Games et GOG",
        "icon": "🦸",
        "windows_id": "HeroicGamesLauncher.HeroicGamesLauncher",
        "linux_id": "com.heroicgameslauncher.hgl",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "lutris",
        "name": "Lutris",
        "category": "Gaming",
        "desc": "Gestionnaire de jeux universel open-source pour Linux",
        "icon": "🍷",
        "windows_id": "",
        "linux_id": "net.lutris.Lutris",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "retroarch",
        "name": "RetroArch",
        "category": "Gaming",
        "desc": "Frontend puissant pour émulateurs de consoles rétro",
        "icon": "🕹️",
        "windows_id": "Libretro.RetroArch",
        "linux_id": "org.libretro.RetroArch",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- MUSIQUE & MÉDIAS ---
    {
        "id": "deezer",
        "name": "Deezer",
        "category": "Musique & Médias",
        "desc": "Application officielle de streaming musical Deezer",
        "icon": "🎵",
        "windows_id": "Deezer.Deezer",
        "linux_id": "dev.aunetx.deezer",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "spotify",
        "name": "Spotify",
        "category": "Musique & Médias",
        "desc": "Service de streaming musical et podcasts leader mondial",
        "icon": "🎧",
        "windows_id": "Spotify.Spotify",
        "linux_id": "com.spotify.Client",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "vlc",
        "name": "VLC Media Player",
        "category": "Musique & Médias",
        "desc": "Lecteur multimédia universel lisant tous les formats vidéo et audio",
        "icon": "🎬",
        "windows_id": "VideoLAN.VLC",
        "linux_id": "org.videolan.VLC",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "obs",
        "name": "OBS Studio",
        "category": "Musique & Médias",
        "desc": "Logiciel de référence pour l'enregistrement vidéo et le live streaming",
        "icon": "🎙️",
        "windows_id": "OBSProject.OBSStudio",
        "linux_id": "com.obsproject.Studio",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "audacity",
        "name": "Audacity",
        "category": "Musique & Médias",
        "desc": "Éditeur et enregistreur audio multipiste libre et gratuit",
        "icon": "🎛️",
        "windows_id": "Audacity.Audacity",
        "linux_id": "org.audacityteam.Audacity",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "handbrake",
        "name": "HandBrake",
        "category": "Musique & Médias",
        "desc": "Convertisseur vidéo open-source puissant tous formats",
        "icon": "🎞️",
        "windows_id": "HandBrake.HandBrake",
        "linux_id": "fr.handbrake.ghb",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- DÉVELOPPEMENT ---
    {
        "id": "vscode",
        "name": "Visual Studio Code",
        "category": "Développement",
        "desc": "Éditeur de code moderne extensible développé par Microsoft",
        "icon": "💻",
        "windows_id": "Microsoft.VisualStudioCode",
        "linux_id": "com.visualstudio.code",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "git",
        "name": "Git",
        "category": "Développement",
        "desc": "Système de contrôle de version distribué incontournable",
        "icon": "🌿",
        "windows_id": "Git.Git",
        "linux_id": "git",
        "linux_type": "system",
        "recommended": True,
    },
    {
        "id": "nodejs",
        "name": "Node.js (LTS)",
        "category": "Développement",
        "desc": "Environnement d'exécution JavaScript côté serveur",
        "icon": "🟢",
        "windows_id": "OpenJS.NodeJS.LTS",
        "linux_id": "nodejs",
        "linux_type": "system",
        "recommended": True,
    },
    {
        "id": "python",
        "name": "Python 3",
        "category": "Développement",
        "desc": "Langage de programmation polyvalent et populaire",
        "icon": "🐍",
        "windows_id": "Python.Python.3.12",
        "linux_id": "python3",
        "linux_type": "system",
        "recommended": False,
    },
    {
        "id": "postman",
        "name": "Postman",
        "category": "Développement",
        "desc": "Outil complet pour concevoir, tester et documenter les API REST",
        "icon": "📮",
        "windows_id": "Postman.Postman",
        "linux_id": "com.getpostman.Postman",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "dbeaver",
        "name": "DBeaver Community",
        "category": "Développement",
        "desc": "Gestionnaire universel de bases de données (SQL, NoSQL)",
        "icon": "🦫",
        "windows_id": "dbeaver.dbeaver",
        "linux_id": "io.dbeaver.DBeaverCommunity",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "sublimetext",
        "name": "Sublime Text",
        "category": "Développement",
        "desc": "Éditeur de texte ultra-rapide pour code et prose",
        "icon": "📝",
        "windows_id": "SublimeHQ.SublimeText.4",
        "linux_id": "com.sublimetext.three",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- UTILITAIRES & SÉCURITÉ ---
    {
        "id": "7zip",
        "name": "7-Zip",
        "category": "Utilitaires & Sécurité",
        "desc": "Extracteur d'archives haute compression (ZIP, 7z, RAR, TAR)",
        "icon": "📦",
        "windows_id": "7zip.7zip",
        "linux_id": "org.7_zip.7_zip",
        "linux_type": "flatpak",
        "recommended": True,
    },
    {
        "id": "notepadplusplus",
        "name": "Notepad++",
        "category": "Utilitaires & Sécurité",
        "desc": "Éditeur de texte léger avec coloration syntaxique",
        "icon": "📋",
        "windows_id": "Notepad++.Notepad++",
        "linux_id": "org.notepad_plus_plus.Notepad-plus-plus",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "powertoys",
        "name": "Microsoft PowerToys",
        "category": "Utilitaires & Sécurité",
        "desc": "Ensemble d'utilitaires système indispensables pour Windows",
        "icon": "⚙️",
        "windows_id": "Microsoft.PowerToys",
        "linux_id": "",
        "linux_type": "none",
        "recommended": False,
    },
    {
        "id": "bitwarden",
        "name": "Bitwarden",
        "category": "Utilitaires & Sécurité",
        "desc": "Gestionnaire de mots de passe sécurisé et open-source",
        "icon": "🛡️",
        "windows_id": "Bitwarden.Bitwarden",
        "linux_id": "com.bitwarden.desktop",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "keepassxc",
        "name": "KeePassXC",
        "category": "Utilitaires & Sécurité",
        "desc": "Coffre-fort de mots de passe sécurisé hors-ligne",
        "icon": "🔑",
        "windows_id": "KeePassXCTeam.KeePassXC",
        "linux_id": "org.keepassxc.KeePassXC",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "qbittorrent",
        "name": "qBittorrent",
        "category": "Utilitaires & Sécurité",
        "desc": "Client torrent libre, rapide et sans publicité",
        "icon": "🧲",
        "windows_id": "qBittorrent.qBittorrent",
        "linux_id": "org.qbittorrent.qBittorrent",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "bleachbit",
        "name": "BleachBit",
        "category": "Utilitaires & Sécurité",
        "desc": "Nettoyeur de fichiers temporaires et cache système",
        "icon": "🧹",
        "windows_id": "BleachBit.BleachBit",
        "linux_id": "org.bleachbit.BleachBit",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- GRAPHISME & CRÉATION ---
    {
        "id": "gimp",
        "name": "GIMP",
        "category": "Graphisme & Création",
        "desc": "Éditeur d'images matricielles et retouche photo complet",
        "icon": "🎨",
        "windows_id": "GIMP.GIMP",
        "linux_id": "org.gimp.GIMP",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "inkscape",
        "name": "Inkscape",
        "category": "Graphisme & Création",
        "desc": "Éditeur de graphismes vectoriels professionnel (SVG)",
        "icon": "✒️",
        "windows_id": "Inkscape.Inkscape",
        "linux_id": "org.inkscape.Inkscape",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "blender",
        "name": "Blender",
        "category": "Graphisme & Création",
        "desc": "Suite complète de création 3D, animation, rendu et effets",
        "icon": "🧊",
        "windows_id": "BlenderFoundation.Blender",
        "linux_id": "org.blender.Blender",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "krita",
        "name": "Krita",
        "category": "Graphisme & Création",
        "desc": "Studio de peinture numérique et illustration professionnelle",
        "icon": "🖌️",
        "windows_id": "KDE.Krita",
        "linux_id": "org.kde.krita",
        "linux_type": "flatpak",
        "recommended": False,
    },

    # --- BUREAUTIQUE ---
    {
        "id": "libreoffice",
        "name": "LibreOffice",
        "category": "Bureautique",
        "desc": "Suite bureautique complète (Writer, Calc, Impress)",
        "icon": "📄",
        "windows_id": "TheDocumentFoundation.LibreOffice",
        "linux_id": "org.libreoffice.LibreOffice",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "obsidian",
        "name": "Obsidian",
        "category": "Bureautique",
        "desc": "Base de connaissances personnelle et prise de notes Markdown",
        "icon": "💎",
        "windows_id": "Obsidian.Obsidian",
        "linux_id": "md.obsidian.Obsidian",
        "linux_type": "flatpak",
        "recommended": False,
    },
    {
        "id": "notion",
        "name": "Notion",
        "category": "Bureautique",
        "desc": "Espace de travail connecté pour notes, wikis et gestion de projets",
        "icon": "📓",
        "windows_id": "Notion.Notion",
        "linux_id": "io.github.notion_enhancer.notion-repackaged",
        "linux_type": "flatpak",
        "recommended": False,
    }
]


def get_catalog():
    """Retourne une copie de la liste des applications."""
    return [dict(app) for app in DEFAULT_CATALOG]
